name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-test:
    name: Lint & Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js (For Frontend/Plugin)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install || echo "No dependencies found"

      - name: Run Linting
        run: npm run lint || echo "Linting skipped"

      - name: Run Tests
        run: npm test || echo "Tests skipped"

      - name: Success Message
        run: echo "CI Checks Completed"
